include="~~/profiles.conf"

# ========== VIDEO ==========
vo=gpu-next
gpu-api=d3d11
hwdec=auto-safe
profile=Film

# Window size cố định
autofit=70%x70%
keepaspect-window=yes

# ========== AUDIO (mặc định: giữ nguyên) ==========

audio-api=wasapi
audio-exclusive=yes
audio-samplerate=auto

# Mặc định: không đụng vào kênh, không filter
audio-channels=auto
audio-normalize-downmix=no
af=clr

audio-file-auto=fuzzy
audio-pitch-correction=yes
volume=90
volume-max=100


# ========== CACHE ==========
cache=auto
demuxer-max-bytes=256MiB
demuxer-readahead-secs=60
demuxer-max-back-bytes=128MiB

# ========== UI ==========
osd-bar=no
osc=no
border=no
cursor-autohide=1000

# ========== SUBTITLES ==========
track-auto-selection=yes
alang=ja,jp,jpn,vi,vie,en,eng
slang=vi,vie
sub-auto=fuzzy
sub-file-paths-append=sub
sub-file-paths-append=subs
sub-file-paths-append=subtitles
