# ================== CORE ==================

[Balanced]
glsl-shaders-clr
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
correct-downscaling=yes
sigmoid-upscaling=yes
dither-depth=auto
temporal-dither=yes


# ================== FILM ==================

[Safe_NoShader]
profile=Balanced
glsl-shaders-clr

# Profile mặc định + 4K native gộp chung
[Film]
profile=Balanced

# Film nâng chất lượng (không quá nặng, ổn định)
[Film_HQ]
profile=Balanced
glsl-shaders-clr
glsl-shader=~~/shaders/ravu-lite-ar-r4.hook
glsl-shader=~~/shaders/CfL_Prediction.glsl


# Phim trắng đen (chỉ bật khi bạn chọn tay)
[Film_BW_Upscale]
profile=Balanced
glsl-shaders-clr
glsl-shader=~~/shaders/FSRCNNX_x2_16-0-4-1.glsl
glsl-shader=~~/shaders/KrigBilateral.glsl
glsl-shader=~~/shaders/filmgrain.glsl
vf=format=gray


# ================== ANIME ==================

[Anime_HQ]
profile=Balanced
glsl-shaders-clr
glsl-shader=~~/shaders/hdeband.glsl
glsl-shader=~~/shaders/FSRCNNX_x2_16-0-4-1.glsl
glsl-shader=~~/shaders/KrigBilateral.glsl

[Anime_LQ]
profile=Balanced
glsl-shaders-clr
glsl-shader=~~/shaders/hdeband.glsl
glsl-shader=~~/shaders/FSRCNNX_x2_8-0-4-1.glsl
glsl-shader=~~/shaders/KrigBilateral.glsl
glsl-shader=~~/shaders/filmgrain.glsl


# ================== FAST ==================

[Fast]
glsl-shaders-clr
scale=bilinear
cscale=bilinear
dscale=bilinear
correct-downscaling=no
sigmoid-upscaling=no
dither=no


# ================== HDR AUTO ==================

[SDR]
profile-cond=!video-params/hdr-metadata
tone-mapping=no

[HDR]
profile-cond=video-params/hdr-metadata
tone-mapping=bt.2390
hdr-compute-peak=yes
hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30
allow-delayed-peak-detect=yes
libplacebo-opts-append=gamut_expansion=yes,perceptual_deadzone=0.4,perceptual_strength=0.5

# ================== AUDIO PROFILES ==================

# 1) PURE: giữ nguyên, không downmix, không filter
[Audio_Pure]
profile-restore=copy-equal
audio-channels=auto
audio-normalize-downmix=no
af=clr
volume=90

# 2) MOVIE: downmix cho phim >2 kênh, tối ưu dàn 2.1 của bạn
[Audio_Movie]
profile-restore=copy-equal
audio-channels=stereo
audio-normalize-downmix=no
af=lavfi="pan=stereo|FL=0.80*FL+0.50*FC+0.30*SL+0.25*LFE|FR=0.80*FR+0.50*FC+0.30*SR+0.25*LFE"
volume=88

# 3) NIGHT: giống Movie nhưng thêm compressor + giảm volume
[Audio_Night]
profile-restore=copy-equal
audio-channels=stereo
audio-normalize-downmix=yes
af=lavfi="pan=stereo|FL=0.80*FL+0.50*FC+0.30*SL+0.25*LFE|FR=0.80*FR+0.50*FC+0.30*SR+0.25*LFE,acompressor=threshold=-24dB:ratio=4:attack=5:release=150"
volume=80

# 4) AUTO: nếu source có >2 kênh thì tự áp Audio_Movie
[Auto_Movie_Downmix]
profile-cond=audio-params/channels>2
profile=Audio_Movie


